version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: ai_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: research_db
      MYSQL_USER: research_user
      MYSQL_PASSWORD: research_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  flask:
    build: .
    container_name: ai_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DB_MODE=docker
      - MYSQL_HOST=db
      - MYSQL_USER=research_user
      - MYSQL_PASSWORD=research_pass
      - MYSQL_DB=research_db
    volumes:
      - .:/app

volumes:
  db_data:
